# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nugetConfigPath: '$(Build.SourcesDirectory)/nuget.config'
  solution: '**/*.sln'
  dockerComposeTestPath: '$(Build.SourcesDirectory)/tests/Edf.Services.ApplicationRegistry.IntegrationTests/docker-compose.yml'
  
steps:

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Edf-DevOps'
    KeyVaultName: 'Edf-DevOps'
    SecretsFilter: '*'

- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@0

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sources update -name edf -configfile "$(nugetConfigPath)" -username "$(ArtifactsPAT)" -password "$(ArtifactsPAT)" -storepasswordincleartext'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'


- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    
- script: |
    docker-compose -f "$(dockerComposeTestPath)" up -d
    dotnet test
  displayName: Setup Testing Environment and Run Tests
  env:
    ASPNETCORE_ENVIRONMENT: ci
    

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
